// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PasigSystem.Server.Models
{
    public partial class PaypalTransaction
    {
        public long PaypalTransactionId { get; set; }
        public string OrderId { get; set; }
        public decimal OrderAmount { get; set; }
        public string UserEmail { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
    }
}